### ISSUE TITLE
fputc/printf() do not seem to work.

### ISSUE THREAD

**Issue by davidmolony** [dekuNukem/STM32_tutorials#1]
I did exactly as described, while using a Nucleo F042k6.

My main while loop includes:
`HAL_Delay(500);
HAL_UART_Transmit(&huart2,(uint8_t*)"hello\r",7,10);
HAL_Delay(500);

char lol[32];
sprintf(lol, "lol %u \r", (unsigned int)10);
HAL_UART_Transmit(&huart2, (uint8_t*)lol, strlen(lol),5);
HAL_Delay(500);
printf("Hello from printf");

`
with the fputc copied and pasted from your example. 
`/* USER CODE BEGIN 0 */
int fputc(int ch, FILE *f)
{
    HAL_UART_Transmit(&huart2, (unsigned char *)&ch, 1, 100);
    return ch;
}
/* USER CODE END 0 */
`
It all compiles fine. Uploads... no indication of a problem except printf simply does nothing.
The sprintf lol business was my old method of printing strings before I found your tutorial.

In the terminal, I get:
`.lol 10 
hello
.lol 10 
hello
.lol 10 
hello
.lol 10 
hello
.lol 10 
hello
`
Is this method tested? Any idea what's going wrong?

**Comment by dekuNukem** [comment]
Hi David:

I would make sure the `fputc()` is at the beginning of the program in main.c, for example in between the `/* USER CODE BEGIN 0 */` and `/* USER CODE END 0 */`, although it looks like it already does.

Maybe try clean up the code and leave only printf and delay in the main loop, something [like this.](https://github.com/dekuNukem/STM32_tutorials/blob/master/lesson1_serial_helloworld/sample_code/Src/main.c)

And also make sure you have chosen the correct chip in STM32CubeMX.

It would be better if you can show me the entire code, assuming everything is in main.c, maybe you can [paste it into gist](https://gist.github.com/).

It has always worked for me, although I usually design my own boards instead using a dev board.

**Comment by davidmolony** [comment]
I have uploaded it to a github repo.
https://github.com/davidmolony/F042-USARTtest

The correct chip is definitely selected - as i the original issue, it IS outputting to the huart2 when I use the HAL function directly.

I also have a few breakout boards I program via J-link, but for trying things out I use the nucleos; just much easier. Fewer wires flapping about.

**Comment by davidmolony** [comment]
It appears from stepping through the program that the printf function simply doesn't compile to actually do anything atall; the function doesn't go anywhere, whereas the direct calls to the HAL library go into a web of stuff.

I'm compiling with GNUC compiler, linker etc as below via eclipse/system workbench for stm32. I see you are using the ARM Keil compiler, perhaps that's the problem.
MCU GCC Compiler
MCU G++ Compiler
MCU GCC Linker
MCU G++ Linker
MCU GCC Archiver
MCU GCC Assembler

**Comment by dekuNukem** [comment]
Oh that was probably it, I did use the default compiler that comes with Keil uVision 5, as is this entire tutorial. ST provides a free licence for all STM32F0 parts, so it's less complicated this way.
